name: 🛠️ Build Astro Project (CI)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Astro Project
        # Si esto funciona, significa que tu código está libre de errores fatales
        run: npm run build
